version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  test-ruby:
    docker:
      - image: cimg/ruby:3.3.4-node
      - image: circleci/postgres:9.5-alpine
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.4.18
      - run:
          name: Set up database configuration
          command: cp config/database.yml.ci config/database.yml
      - run:
          name: wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
            bundle exec rake db:test:prepare
      - run:
          name: rspec test
          command: bundle exec rspec
workflows:
  build-and-test:
    jobs:
      - test-ruby
