version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  test-ruby:
    docker:
      - image: cimg/ruby:3.3.4-node
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: persogen_test
    environment:
      RAILS_ENV: test
      PGHOST: 127.0.0.1
      POSTGRES_USER: postgres
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for Postgres
          command: |
            dockerize -wait tcp://127.0.0.1:5432 -timeout 30s
      - run:
          name: Database setup
          command: |
            bundle exec rails db:setup
      - run:
          name: Run tests
          command: bundle exec rspec
workflows:
  build-and-test:
    jobs:
      - test-ruby
